### ISSUE TITLE
Backend of game is initialized and gives first call to respond to

### ISSUE THREAD

**Issue by wsuchanek** [wsuchanek/JDRWChess#17]
Epic: Start Game

Chess game is instantiated in back end. 

Done: The back end is there, and to show this is done, when game is instantiated the API returns a message with the color of the user, and the difficulty of the game. This should show the connection between the two ends.

**Comment by ssandhu03** [comment]
jot

**Comment by ssandhu03** [comment]
3/25 - 3/26   Broke down ant structure to create middle Api, but no success in creating an API.(tried using JUNIT to create a test that tests the user color, but failed)
3 hours

**Comment by ssandhu03** [comment]
3/28 Found new Chess game and in Junit wrote test that initializes game, and tests to make sure the board is created correctly and that coordinates translate correctly.

How this moves towards goal:
   Junit test shows that the game can be initialized in the backend, although it doesn't return a message with color, the test for the chess pieces also shows the connection between front end and back end.

2 hours

**Comment by wsuchanek** [comment]
Changed all .class files to .java files and moved them into a src folder instead of the current out folder. Created proper packages and fixed imports to get all code functional and working. General fixes to file structure of DanChunn (including moving to the root level of the project).

2 Hours
