### ISSUE TITLE
Alexa Reading + Sample Code

### ISSUE THREAD

**Issue by wsuchanek** [wsuchanek/JDRWChess#26]
Read the Alexa Skills Kit reading (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/using-the-alexa-skills-kit-samples)

And view and run the example code to get a better understanding of how Alexa works (In our Git)

Done: Reading is read and example code was ran

**Comment by wsuchanek** [comment]
20 hours between everyone, everyone should post the amount of time they spent reading in here individually

**Comment by wsuchanek** [comment]
Time spent getting lambda functional with the helloworld app as well as reading through 

4 Hours

**Comment by wsuchanek** [comment]
Fixed Lambda issue for helloworld, tried looking more into score keeper but there must be an error in the example code, tried recreating lambdas and skill to no success

3 hours

**Comment by ssandhu03** [comment]
3/22 Time spent reading Alexa tutorial as well as building HelloWorld( Done in python)
1 hour

3/25-3/26    Tried to work through score keeper example, but couldn't get it to work
2 hours
