### ISSUE TITLE
Automate opponent

### ISSUE THREAD

**Issue by wsuchanek** [wsuchanek/JDRWChess#28]
There is an AI(computer) player that can pick its own moves at random to play against the human in chess.

Done: opponent picks random legal moves and makes them. These moves will be shown on the board.

**Comment by ssandhu03** [comment]
4/2/17 Created an AI for the opponent. It randomly picks a piece on the opponents side and then picks the closest spot towards the opponents end of the board as the spot it moves to.
as a result right now where the piece moves is not random, but which piece moves is random.
6 hours
