### ISSUE TITLE
Read in save Text File

### ISSUE THREAD

**Issue by wsuchanek** [wsuchanek/JDRWChess#33]
Resume Game Epic

Read in text file and and create a list of moves which will be used to resume the game

**Comment by GitMasterDray** [comment]
what will the output of this function be?

**Comment by wsuchanek** [comment]
Own new class, in the /DanChunn/src/production/DanChunn/util

output is arraylist of strings, each line is it's own item in arraylist, .i.e., ["a2 a3", "b7 b6"]
